# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media/img'),
            preserve_default=False,
        ),
    ]
