# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default.png', upload_to='img'),
            preserve_default=False,
        ),
    ]
